In [1]:
%matplotlib inline
import numpy as np
import pylab

In [2]:
dates = np.array([[2017, 10, 1], [2017, 10, 2], [2017, 10, 13], [2017, 10, 27.0]])
dates

array([[  2.01700000e+03,   1.00000000e+01,   1.00000000e+00],
       [  2.01700000e+03,   1.00000000e+01,   2.00000000e+00],
       [  2.01700000e+03,   1.00000000e+01,   1.30000000e+01],
       [  2.01700000e+03,   1.00000000e+01,   2.70000000e+01]])

In [10]:
from datetime import date
dow=[]
for i in range(len(dates)):
    d=date(int(dates[i,0]),int(dates[i,1]),int(dates[i,2]))
    dow.append(d.weekday())
dow=np.array(dow)
dow

array([6, 0, 4, 4])

In [16]:
dow=np.arange(30) %7
dow

array([0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1,
       2, 3, 4, 5, 6, 0, 1])

In [14]:
rainfall= np.random.random(30)
rainfall

array([ 0.83105846,  0.79973773,  0.50802209,  0.12228716,  0.57958969,
        0.93884318,  0.90636363,  0.71915776,  0.99471184,  0.49990651,
        0.85242313,  0.24474208,  0.78219241,  0.93943956,  0.67542693,
        0.16888569,  0.30377467,  0.9427225 ,  0.96180576,  0.28150274,
        0.21476718,  0.05094767,  0.70974547,  0.45758403,  0.6627613 ,
        0.33606483,  0.0307693 ,  0.34138122,  0.79781167,  0.9960088 ])

In [18]:
r=0
for i in range(len(dow)):
    if dow[i]==6:
        r=r+rainfall[i]
print(r)

2.40195159145


In [19]:
np.sum(rainfall[dow==6])

2.4019515914471237

In [22]:
np.sum(rainfall[(dow==6)|(dow==5)])

4.4352592204604093

In [23]:
np.sum(rainfall[(dow>=1)&(dow<=3)])

8.0185709269046974

In [24]:
np.random.permutation(dow)

array([3, 2, 2, 6, 5, 4, 6, 1, 5, 1, 0, 2, 3, 0, 0, 5, 2, 4, 1, 5, 0, 4, 0,
       3, 3, 1, 6, 6, 1, 4])