In [1]:
%matplotlib inline
import numpy as np
import pylab

Write a function f1 that takes an array as its only argument and returns the sum of the elements of the array. Of course you could do this with np.sum but don't use it for this practice.


In [2]:
np.random.seed(0)
A = np.random.randint(0, 100, (4, 5))
A

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88]])

In [3]:
A[1,1]

83

In [4]:
A[1]

array([ 9, 83, 21, 36, 87])

In [5]:
A[1][1]

83

In [6]:
A[1:3,1:4]

array([[83, 21, 36],
       [88, 88, 12]])

In [7]:
A[1:3][1:4]

array([[70, 88, 88, 12, 58]])

In [8]:
A[1:3]

array([[ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58]])

In [9]:
def f1(A):
    s=0
    for i in range(len(A)):
        s= s+A[i]
    return s

In [11]:
b= np.array([42,17,63,54,57])

In [12]:
f1(b)

233

Write **f2** that takes on array as its only argument adn returns a list with the array elements squared

In [14]:
def f2(A):
    r=np.zeros_like(A)
    for i in range(len(A)):
        r[i]=(A[i]**2)
    return r
f2(b)
    

array([1764,  289, 3969, 2916, 3249])

Write **f3** that takes two arguments:an array and a function. it should return a list of the results of apply the function to each value in the array

In [16]:
def f3(A,f):
    r=[]
    for i in range(len(A)):
        r.append(f(A[i]))
    return r
def g(x):
    return x**2
f3(b,g )

[1764, 289, 3969, 2916, 3249]

In [18]:
def f3a(A,f):
    for i in range(len(A)):
        r=[]
        r.append(f(A[i]))
    return r
def g(x):
    return x**2
f3a(b,g)

[3249]

In [19]:
r=[]
def f3b(A,f):
    for i in range(len(A)):
        r.append(f(A[i]))
    return r
def g(x):
    return x**2
f3b(b,g)

[1764, 289, 3969, 2916, 3249]

In [20]:
f3b(b,g)

[1764, 289, 3969, 2916, 3249, 1764, 289, 3969, 2916, 3249]