In [11]:
%matplotlib inline
import numpy as np
import pylab

simulate rolling a 6 sided dice

In [12]:
np.random.seed(0)
rolls = np.random.randint(1,7,20)
rolls

array([5, 6, 1, 4, 4, 4, 2, 4, 6, 3, 5, 1, 1, 5, 3, 2, 1, 2, 6, 2])

Write a function to count the number of times each number
appears in a sequence. Your function might return
array([0, 4, 4, 2, 4, 3, 3]) for the input array([5, 6, 1, 4, 4, 4, 2, 4, 6, 3, 5, 1, 1, 5, 3, 2, 1, 2, 6, 2])
because 0 occurred not at all, 1 occurs 4 times, 2 occurs
4 times, etc.


In [13]:
def count5(seq):
    count=0
    for i in range(len(seq)):
        if seq[i]==5:
            count=count +1
    return count
count5(rolls)

3

In [14]:
def count5n(seq):
    return np.count_nonzero(seq==5)
count5n(rolls)

3

In [15]:
def count(seq):
    result= []
    for n in range(1,7):
        result.append(np.count_nonzero(seq==n))
    return result
count(rolls)

[4, 4, 2, 4, 3, 3]

In [16]:
def count(seq):
    result= []
    for n in range(1,7):
        count=0
        for i in range(len(seq)):
            if seq[i]==n:
                count= count +1
        result.append(count)
    return result
count(rolls)

[4, 4, 2, 4, 3, 3]

In [17]:
def count(seq):
    result = []
    for n in range(np.min(seq),np.max(seq)+1):
        count = 0
        for i in range(len(seq)):
            if seq[i] == n:
                count = count + 1
        result.append(count)
    return result
count(rolls)

[4, 4, 2, 4, 3, 3]

In [18]:
count(np.random.randint(10,100,20))


[2,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 2,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1]

In [20]:
np.bincount(rolls)

array([0, 4, 4, 2, 4, 3, 3])

In [27]:
def count1(seq):
    result=np.zeros(np.max(seq)+1, dtype=int)
    for i in range(len(seq)):
        n=seq[i]
        result[n]= result[n]+1
    return result

In [28]:
count1(rolls)

array([0, 4, 4, 2, 4, 3, 3])

d{}== empty dictionary

In [29]:
def countDecorated(seq):
    result = np.zeros(np.max(seq)+1, dtype=int)
    print(result)
    for i in range(len(seq)):
        n = seq[i]
        result[n] = result[n] + 1
        print(result)
    return result
countDecorated(rolls)

[0 0 0 0 0 0 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 1]
[0 1 0 0 0 1 1]
[0 1 0 0 1 1 1]
[0 1 0 0 2 1 1]
[0 1 0 0 3 1 1]
[0 1 1 0 3 1 1]
[0 1 1 0 4 1 1]
[0 1 1 0 4 1 2]
[0 1 1 1 4 1 2]
[0 1 1 1 4 2 2]
[0 2 1 1 4 2 2]
[0 3 1 1 4 2 2]
[0 3 1 1 4 3 2]
[0 3 1 2 4 3 2]
[0 3 2 2 4 3 2]
[0 4 2 2 4 3 2]
[0 4 3 2 4 3 2]
[0 4 3 2 4 3 3]
[0 4 4 2 4 3 3]


array([0, 4, 4, 2, 4, 3, 3])

In [35]:
d={}
d['foo']='hello world'
d

{'foo': 'hello world'}

In [36]:
d['foo']

'hello world'

In [40]:
d[5]=25
d

{'foo': 'hello world', 5: 25}

In [41]:
d[1234567]='all good children go to heaven'

In [42]:
d

{'foo': 'hello world', 5: 25, 1234567: 'all good children go to heaven'}