## Notes for 20 November - Consecutive primes anomaly
Prime numbers have been studied for centuries but a strange property of their last digits has just been noticed in March of 2016. You can read the paper on arxiv or a more approachable account in Scientific American or Quanta. If you find prime numbers interesting, I highly recommend the book Prime Obsession by John Derbyshire.
Today we will attempt to confirm this amazing finding that the last digits of consecutive prime numbers are more likely to be different than the same.
I found a list of the first million primes online and reformatted it to make it easy for you to download.

In [1]:
%matplotlib inline
import numpy as np
import pylab

#load the list of the first million primes
primes = np.genfromtxt("http://wwwx.cs.unc.edu/Courses/comp116-f17/media/primes.txt",
                      dtype=int)

In [2]:
len(primes)

1000000

In [4]:
primes[:20]

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71])

In [5]:
B=10

In [7]:
p=53
p%B

3

In [9]:
def countLastDigit(prime,base):
    r=[]
    for n in range(1,10):
        r.append(np.count_nonzero(prime%base == n))
    return r
countLastDigit(primes, 10)

[249934, 1, 250110, 0, 1, 0, 250014, 0, 249940]

In [15]:
def CountLastDigit(primes, base):
    result= np.zeros(base, dtype=int)
    for i in range(len(primes)):
        d=primes[i]%base
        result[d]=result[d]+1
    return result

In [16]:
CountLastDigit(primes,10)

array([     0, 249934,      1, 250110,      0,      1,      0, 250014,
            0, 249940])

In [17]:
def countLastDigitDictionary(primes, base):
    result = {}
    for i in range(len(primes)):
        d = primes[i] % base
        if d in result:
            result[d] += 1
        else:
            result[d] = 1
    return result

In [18]:
countLastDigitDictionary(primes,10)

{1: 249934, 2: 1, 3: 250110, 5: 1, 7: 250014, 9: 249940}

In [19]:
def countLastDigitDictionary1(primes, base):
    result = {}
    for i in range(len(primes)):
        d = primes[i] % base
        result[d]= result.get(d,0)+1
    return result

In [20]:
countLastDigitDictionary1(primes,10)

{1: 249934, 2: 1, 3: 250110, 5: 1, 7: 250014, 9: 249940}

In [23]:
def countlastconsecutivedigit(prime, base):
    result=np.zeros((base,base), dtype=int)
    for i in range(1,len(primes)):
        d1=prime[i-1]%base
        d2=prime[i]%base
        result[d1,d2]+=1
    return result
countlastconsecutivedigit(primes,10)

array([[    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0, 42853,     0, 77475,     0,     0,     0, 79453,     0,
        50153],
       [    0,     0,     0,     1,     0,     0,     0,     0,     0,
            0],
       [    0, 58255,     0, 39668,     0,     1,     0, 72827,     0,
        79358],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     1,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0, 64230,     0, 68595,     0,     0,     0, 39603,     0,
        77586],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0, 84596,     0, 64371,     0,     0,     0, 58130,     0,
        42843]])

In [25]:
def countlastconsecutivedigitdictionary(prime,base):
    result={}
    for i in range(1,len(primes)):
        d1=prime[i-1]%base
        d2=prime[i]%base
        key=(d1,d2)
        result[key]=result.get(key,0)+1
    return result
countlastconsecutivedigitdictionary(primes,10)

{(1, 1): 42853,
 (1, 3): 77475,
 (1, 7): 79453,
 (1, 9): 50153,
 (2, 3): 1,
 (3, 1): 58255,
 (3, 3): 39668,
 (3, 5): 1,
 (3, 7): 72827,
 (3, 9): 79358,
 (5, 7): 1,
 (7, 1): 64230,
 (7, 3): 68595,
 (7, 7): 39603,
 (7, 9): 77586,
 (9, 1): 84596,
 (9, 3): 64371,
 (9, 7): 58130,
 (9, 9): 42843}

In [26]:
countlastconsecutivedigitdictionary(primes,3)

{(0, 2): 1,
 (1, 1): 215873,
 (1, 2): 283955,
 (2, 0): 1,
 (2, 1): 283956,
 (2, 2): 216213}

In [27]:
countlastconsecutivedigitdictionary(primes,6)

{(1, 1): 215873,
 (1, 5): 283955,
 (2, 3): 1,
 (3, 5): 1,
 (5, 1): 283956,
 (5, 5): 216213}

In [28]:
countlastconsecutivedigitdictionary(primes,16)

{(1, 1): 6900,
 (1, 3): 21071,
 (1, 5): 17326,
 (1, 7): 23453,
 (1, 9): 14482,
 (1, 11): 14129,
 (1, 13): 15992,
 (1, 15): 11505,
 (2, 3): 1,
 (3, 1): 11460,
 (3, 3): 6921,
 (3, 5): 21247,
 (3, 7): 17522,
 (3, 9): 23592,
 (3, 11): 14469,
 (3, 13): 14125,
 (3, 15): 15780,
 (5, 1): 15778,
 (5, 3): 11623,
 (5, 5): 6938,
 (5, 7): 20917,
 (5, 9): 17367,
 (5, 11): 23578,
 (5, 13): 14536,
 (5, 15): 14194,
 (7, 1): 14215,
 (7, 3): 15763,
 (7, 5): 11512,
 (7, 7): 7012,
 (7, 9): 21038,
 (7, 11): 17401,
 (7, 13): 23540,
 (7, 15): 14519,
 (9, 1): 14457,
 (9, 3): 14262,
 (9, 5): 15701,
 (9, 7): 11570,
 (9, 9): 6863,
 (9, 11): 21163,
 (9, 13): 17276,
 (9, 15): 23646,
 (11, 1): 23663,
 (11, 3): 14442,
 (11, 5): 14055,
 (11, 7): 15857,
 (11, 9): 11508,
 (11, 11): 6971,
 (11, 13): 20930,
 (11, 15): 17549,
 (13, 1): 17401,
 (13, 3): 23400,
 (13, 5): 14570,
 (13, 7): 14252,
 (13, 9): 15873,
 (13, 11): 11448,
 (13, 13): 7050,
 (13, 15): 21077,
 (15, 1): 20984,
 (15, 3): 17633,
 (15, 5): 23582,
 (15, 7): 1