In [11]:
%matplotlib inline
import numpy as np
import pylab

In [12]:
A = np.random.randint(0, 10, (4, 3))
A

array([[2, 8, 6],
       [5, 3, 1],
       [7, 7, 5],
       [7, 1, 8]])

In [13]:
for i in range(A.shape[1]):
    print(np.sum(A[:,i]))

21
19
20


In [22]:
data = np.loadtxt('krdu-2001-2010.csv', delimiter=',')
data
ymd = data[:,:3].astype(int)
ymd

array([[2001,    1,    1],
       [2001,    1,    2],
       [2001,    1,    3],
       ..., 
       [2010,   12,   29],
       [2010,   12,   30],
       [2010,   12,   31]])

In [24]:
monthly_total = np.zeros(13)
monthly_count = np.zeros(13)
for i in range(len(data)):
    month = ymd[i, 1]
    monthly_total[month] = monthly_total[month] + data[i, 3]
    monthly_count[month] = monthly_count[month] +1
monthly_total[1:] / monthly_count[1:]

array([ 0.08339961,  0.08695011,  0.14141639,  0.09358393,  0.09587416,
        0.13546837,  0.15607261,  0.15245994,  0.14713597,  0.10044371,
        0.1180842 ,  0.11385294])

In [18]:
import urllib.request
urllib.request.urlretrieve('https://wwwx.cs.unc.edu/Courses/comp116-f17/media/krdu-2001-2010.csv', 'krdu-2001-2010.csv')

('krdu-2001-2010.csv', <http.client.HTTPMessage at 0x117ae3898>)

In [25]:
monthly_total = np.zeros(13)
monthly_count = np.zeros(13)
for i in range(len(data)):
    month = ymd[i, 1]
    monthly_total[month] = monthly_total[month] + data[i, 3]
    monthly_count[month] = monthly_count[month] + 1
    if i % 100 == 0:
        print('i=', i, 'month=', month)
        print('mt=', monthly_total)
        print('mc=', monthly_count)

                             

i= 0 month= 1
mt= [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
mc= [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
i= 100 month= 4
mt= [ 0.       1.30306  2.34247  7.11368  0.80713  0.       0.       0.       0.
  0.       0.       0.       0.     ]
mc= [  0.  31.  28.  31.  11.   0.   0.   0.   0.   0.   0.   0.   0.]
i= 200 month= 7
mt= [ 0.       1.30306  2.34247  7.11368  1.72054  3.53152  4.5395   1.24411
  0.       0.       0.       0.       0.     ]
mc= [  0.  31.  28.  31.  30.  31.  30.  20.   0.   0.   0.   0.   0.]
i= 300 month= 10
mt= [ 0.       1.30306  2.34247  7.11368  1.72054  3.53152  4.5395   4.13791
  4.87766  0.86221  1.86259  0.       0.     ]
mc= [  0.  31.  28.  31.  30.  31.  30.  31.  31.  30.  28.   0.   0.]
i= 400 month= 2
mt= [ 0.       7.27504  2.34247  7.11368  1.72054  3.53152  4.5395   4.13791
  4.87766  0.86221  1.86259  0.50001  2.01582]
mc= [  0.  62.  33.  31.  30.  31.  30.  31.  31.  30.  31.  30.  31.]
i= 500 month= 5
mt= [  0.     

In [26]:
data[:5]

array([[  2.00100000e+03,   1.00000000e+00,   1.00000000e+00,
          0.00000000e+00],
       [  2.00100000e+03,   1.00000000e+00,   2.00000000e+00,
          0.00000000e+00],
       [  2.00100000e+03,   1.00000000e+00,   3.00000000e+00,
          0.00000000e+00],
       [  2.00100000e+03,   1.00000000e+00,   4.00000000e+00,
          0.00000000e+00],
       [  2.00100000e+03,   1.00000000e+00,   5.00000000e+00,
          0.00000000e+00]])