## Midterm 2 preview
We will use these data for Midterm2. They are the same as the data from oldMidterm1.


## Data
You are given a dataset consisting of measured rainfall in inches at several station scattered across North Carolina for many consecutive days. There is a column for each station and a row for each day. That is, a 10 by 4 array represents 10 days with data at 4 stations for each day.
I am not telling you the number of stations or the number of days. You'll have to work those things out. Most importantly, you may not assume the dataset will be the same size when I do the grading. Your answer must work for any reasonable number of stations and days.
I'll load the data for you here. Don't change any of this.

In [12]:
%matplotlib inline
import numpy as np
import pylab

rain = np.loadtxt('rain-Copy1.txt')
rain.setflags(write=False) # don't allow writing the array

In [13]:
rain

array([[ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.03,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.16,  0.28,  0.  ,  0.83,  0.  ],
       [ 2.22,  0.03,  0.  ,  0.01,  0.  ],
       [ 0.03,  0.02,  0.87,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.01,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.19,  0.86,  0.  ,  1.09,  0.  ],
       [ 0.54,  0.35,  1.73,  0.02,  0.  ],
       [ 0.04,  0.04,  0.86,  0.07,  0.  ],
       [ 0.02,  0.  ,  0.02,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.02,  0.39,  0.  ,  0.55,  0.  ],
       [ 0.  ,  0.04,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.27,  0.  ,  0.  ,  0.

In [19]:
A=np.array([42, 17,1954,2000])
np.where(A==1054)

(array([], dtype=int64),)

In [20]:
np.where(A==1954)[0]

array([2])

In [21]:
(A>1900)&(A%2==0)

array([False, False,  True,  True], dtype=bool)

In [23]:
r = []
for i in range(len(A)):
    if A[i] > 1900:
        r.append(A[i])
r

[1954, 2000]

In [24]:
def F1(A):
    r = []
    for i in range(len(A)):
        if A[i] > 1900:
            r.append(A[i])
    return r
F1(A)

[1954, 2000]

In [26]:
tiny=rain[:8,:]
tiny

array([[ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.03,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.16,  0.28,  0.  ,  0.83,  0.  ],
       [ 2.22,  0.03,  0.  ,  0.01,  0.  ],
       [ 0.03,  0.02,  0.87,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.01,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ]])

In [27]:
tiny > 0

array([[False, False, False, False, False],
       [ True, False, False, False, False],
       [ True,  True, False,  True, False],
       [ True,  True, False,  True, False],
       [ True,  True,  True, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]], dtype=bool)

In [28]:
np.count_nonzero(tiny > 0)

11

In [30]:
t=np.count_nonzero(tiny > 0, axis = 1)

In [31]:
r=[]
for i in range(len(t)):
    if t[i]>=2:
        r.append(i)#index when condition was satisfied
r

[2, 3, 4]

In [33]:
def majorityRainyIndexes(d):
    r = []
    isRainy = d > 0
    rainystationcount= np.count_nonzero(isRainy, axis=1)
    threshold= d.shape[1]/2#threshold for majority
    ismajority= rainystationcount>threshold
    for i in range(len(ismajority)):
        if ismajority[i]:
            r.append(i)
    return r
majorityRainyIndexes(rain)

[2,
 3,
 4,
 11,
 12,
 13,
 17,
 23,
 26,
 32,
 33,
 35,
 40,
 41,
 47,
 52,
 53,
 55,
 56,
 60,
 61,
 62,
 63,
 64,
 70,
 72,
 73,
 78,
 79,
 81,
 84,
 85,
 86,
 97,
 98,
 100,
 103,
 104,
 105,
 109,
 115,
 116,
 120,
 127]