In [3]:
%matplotlib inline
import numpy as np
import pylab

In [4]:
np.random.seed(0)
D = np.random.randint(1, 7, (10, 5))
D

array([[5, 6, 1, 4, 4],
       [4, 2, 4, 6, 3],
       [5, 1, 1, 5, 3],
       [2, 1, 2, 6, 2],
       [6, 1, 2, 5, 4],
       [1, 4, 6, 1, 3],
       [4, 1, 2, 4, 6],
       [4, 4, 1, 2, 2],
       [2, 1, 3, 5, 4],
       [4, 3, 5, 3, 1]])

In [4]:
np.any(D > 6)

False

In [5]:
np.any(D > 3)

True

In [6]:
np.any(D > 5, axis=0)

array([ True,  True,  True,  True,  True], dtype=bool)

In [16]:
np.any(D==5, axis=0)

array([ True, False,  True,  True, False], dtype=bool)

In [17]:
np.any(D==5, axis=1)

array([ True, False,  True, False,  True, False, False, False,  True,  True], dtype=bool)

In [18]:
#np.any(depth>216, axis=0) np.any(depth>251.5, axis=1)

In [19]:
np.sum(np.any(D==5, axis=1))

5

In [21]:
~np.any(D==5, axis=1)

array([False,  True, False,  True, False,  True,  True,  True, False, False], dtype=bool)

In [23]:
D[-1,:]

array([4, 3, 5, 3, 1])

In [25]:
D[0,3:5]

array([4, 4])

In [26]:
#doesn't matter how many dice, you will always get the last two
D[0,-2:]

array([4, 4])

In [5]:
len(D)

10

In [6]:
D.shape

(10, 5)

In [7]:
D[len(D)-1,:]

array([4, 3, 5, 3, 1])

In [8]:
#rows become the columns
D.T

array([[5, 4, 5, 2, 6, 1, 4, 4, 2, 4],
       [6, 2, 1, 1, 1, 4, 1, 4, 1, 3],
       [1, 4, 1, 2, 2, 6, 2, 1, 3, 5],
       [4, 6, 5, 6, 5, 1, 4, 2, 5, 3],
       [4, 3, 3, 2, 4, 3, 6, 2, 4, 1]])

In [10]:
D[-1,::-1]

array([1, 3, 5, 3, 4])

In [11]:
#laying them out in the same order
np.reshape(D,(5,10))

array([[5, 6, 1, 4, 4, 4, 2, 4, 6, 3],
       [5, 1, 1, 5, 3, 2, 1, 2, 6, 2],
       [6, 1, 2, 5, 4, 1, 4, 6, 1, 3],
       [4, 1, 2, 4, 6, 4, 4, 1, 2, 2],
       [2, 1, 3, 5, 4, 4, 3, 5, 3, 1]])

In [12]:
D[:,:3]

array([[5, 6, 1],
       [4, 2, 4],
       [5, 1, 1],
       [2, 1, 2],
       [6, 1, 2],
       [1, 4, 6],
       [4, 1, 2],
       [4, 4, 1],
       [2, 1, 3],
       [4, 3, 5]])

In [13]:
D[4:7,1:4]

array([[1, 2, 5],
       [4, 6, 1],
       [1, 2, 4]])

In [15]:
np.count_nonzero(D[4:7,1:4]==1)

3

In [17]:
np.min(D, axis=0)

array([1, 1, 1, 1, 1])

In [18]:
D-np.min(D,axis=0)

array([[4, 5, 0, 3, 3],
       [3, 1, 3, 5, 2],
       [4, 0, 0, 4, 2],
       [1, 0, 1, 5, 1],
       [5, 0, 1, 4, 3],
       [0, 3, 5, 0, 2],
       [3, 0, 1, 3, 5],
       [3, 3, 0, 1, 1],
       [1, 0, 2, 4, 3],
       [3, 2, 4, 2, 0]])