In [13]:
%matplotlib inline
import numpy as np
import pylab

In [15]:
A=np.array([3,5,7,9,11,13])

In [16]:
A

array([ 3,  5,  7,  9, 11, 13])

In [18]:
np.reshape(A, (2,3))

array([[ 3,  5,  7],
       [ 9, 11, 13]])

In [19]:
#last dimention moves the fastest (aka [years, months, days, hours])
A.T

array([ 3,  5,  7,  9, 11, 13])

In [20]:
#np.function(array[start:stop:step])
np.sum(A[1::3])

16

In [21]:
Z=np.zeros(10)

In [23]:
len(Z)

10

In [24]:
np.count_nonzero(Z)

0

In [25]:
A32= np.reshape(A, (3,2))

In [26]:
A32[-1,:]

array([11, 13])