In [1]:
%matplotlib inline
import numpy as np
import pylab

In [2]:
np.random.seed(0)
data = np.random.randint(0, 100, (14,5))
data

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72],
       [ 9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88],
       [49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57],
       [32, 31, 74, 23, 35],
       [75, 55, 28, 34,  0],
       [ 0, 36, 53,  5, 38],
       [17, 79,  4, 42, 58],
       [31,  1, 65, 41, 57]])

A question about finding the index of all of the True values in an array.

In [3]:
b = np.array([0,1,0,0,1], dtype=bool)
b

array([False,  True, False, False,  True], dtype=bool)

Make an array of index values

In [5]:
i = np.arange(5)
i

array([0, 1, 2, 3, 4])

Use boolean selection to extract the indexes of the True values

In [6]:
i[b]

array([1, 4])

In [7]:
w=np.array([3,5,8,2,6,6,2])

In [8]:
np.mean(w)

4.5714285714285712

In [17]:
mw= np.mean(w)
mw

4.5714285714285712

In [18]:
isbigger= w > mw
isbigger

array([False,  True,  True, False,  True,  True, False], dtype=bool)

In [19]:
bigones= w[isbigger]
bigones

array([5, 8, 6, 6])

In [20]:
np.mean(bigones)

6.25

In [22]:
np.random.seed(3)
a3d= np.random.randint(0, 100, (2,3,4))
a3d

array([[[24,  3, 56, 72],
        [ 0, 21, 19, 74],
        [41, 10, 21, 38]],

       [[96, 20, 44, 93],
        [39, 14, 26, 81],
        [90, 22, 66,  2]]])

In [23]:
a3d[0]

array([[24,  3, 56, 72],
       [ 0, 21, 19, 74],
       [41, 10, 21, 38]])

In [24]:
a3d[:,0,:]

array([[24,  3, 56, 72],
       [96, 20, 44, 93]])

In [25]:
a3d[:,:,0]

array([[24,  0, 41],
       [96, 39, 90]])

In [28]:
dataweekly=np.reshape(data, (-1,7,5))
dataweekly

array([[[44, 47, 64, 67, 67],
        [ 9, 83, 21, 36, 87],
        [70, 88, 88, 12, 58],
        [65, 39, 87, 46, 88],
        [81, 37, 25, 77, 72],
        [ 9, 20, 80, 69, 79],
        [47, 64, 82, 99, 88]],

       [[49, 29, 19, 19, 14],
        [39, 32, 65,  9, 57],
        [32, 31, 74, 23, 35],
        [75, 55, 28, 34,  0],
        [ 0, 36, 53,  5, 38],
        [17, 79,  4, 42, 58],
        [31,  1, 65, 41, 57]]])

In [29]:
np.sum(dataweekly, axis=0)

array([[ 93,  76,  83,  86,  81],
       [ 48, 115,  86,  45, 144],
       [102, 119, 162,  35,  93],
       [140,  94, 115,  80,  88],
       [ 81,  73,  78,  82, 110],
       [ 26,  99,  84, 111, 137],
       [ 78,  65, 147, 140, 145]])

In [30]:
np.sum(dataweekly, axis=1)

array([[325, 378, 447, 406, 539],
       [243, 263, 308, 173, 259]])

In [31]:
np.sum(dataweekly, axis=(0,1))

array([568, 641, 755, 579, 798])

midterm notes

distance btw confused variable names== 1

distance btw ((a),a)= 0

distance btw (a,(a))=2

distance btw (np.sum(a, axis=1), np.sum(a, axis=0))=1

distance btw (np.sum(a), np.sum(a, axis=0))=4


numbers in an array = len(n)--1D array

                    = np.size(n)--2D array

Mid term tips:

know numpty function

universal code

check variables

write something down for partial credit