# Worksheet07

This is for your joy, amusement, and edification. Don't think of it as an assignment. Think of it as a chance to exercise your skills. 

You may collaborate with friends, refer to notes, search the web, or use any other resources as you work on the problems below.

Relevant notes are from October 11th

Run the following cell to set everything up.

In [1]:
import numpy as np

#### For loops

1) Print "Hello" 5 times using a for loop

In [2]:
# write your code here
def FiveTimes(x,N):
    r=0
    for i in range(N):
        r= x*N
    return r
FiveTimes("Hello",5)
# starts with for i in range(some number N):
# whatever you put in the body of the for loop will be executed N times
# what do you want to put in the body of the for loop



'HelloHelloHelloHelloHello'

2) Execute the following code 10 times using a for loop: "total = 2*total + 1". I'll print the total at the end for you.

In [3]:
# setup
total = 1
for i in range (10):
    total=2*total+1
        

# write your code here 


# printing total
print(total)

2047


I got 2047

3) Print the values of 1-3 using a for loop. That is, write a for loop that does the same thing as:

print(1) 

print(2) 

print(3)

* Hint: If you have a variable that iterates over the values of 1,2, and 3, you can just print that variable

In [4]:
# write your code here
def printing(x):
    return x
printing('1 2 3')


'1 2 3'

4) Add the value of the index to the x and y values of the cooridinates in coords. For example, coords[1] is (2,3) and we want to turn that into (2+1,3+1) = (3,4) since the value of the index is 1. I'll print coords for you.

In [5]:
coords = np.array([(1,2),(2,3),(3,4)])
coords[1]+int(np.diff(coords[1]))

array([3, 4])

In [6]:
# Setting up coords 
coords = np.array([(1,2),(2,3),(3,4)])
r=[]
for i in range(len(coords)):
    r.append(coords[i]+i)

# write your code here
print(r)
# printing coords


[array([1, 2]), array([3, 4]), array([5, 6])]


I got 

[[1 2]

[3 4]
 
[5 6]]

#### Nested for loops

5) Read this code and think about what will be printed. Run it and see if it matches your expectation.

In [7]:
for i in range(3):
    print('i = %d' %(i)) # print the value of i
    for j in range(5):
        print('j = %d' %(j)) # print the value of j
    print('\n') # leave a blank line before the next execution of i-loop

i = 0
j = 0
j = 1
j = 2
j = 3
j = 4


i = 1
j = 0
j = 1
j = 2
j = 3
j = 4


i = 2
j = 0
j = 1
j = 2
j = 3
j = 4




6) Run this code (you don't have to understant the print statements, just look at how i and j are behaving)

In [8]:
N = 2
M = 3

for i in range(N): 
    #All of the following code is in the body of the for loop iterating over the values of range(N) so it runs N times
    
    for j in range(M):
        
        #All of the following code is in the body of the for loop iterating over the values of range(M)
        #Thus, it runs M times
        #However, since its in the body of the outer for loop which runs N times
        #The following code runs N*M times (do you see why?)
        
        print("This is execution %d of this print statememt" %(i*M + j + 1)) #Don't worry about how this line works
        print("i is %d and j is %d" %(i,j)) #Just printing what the values of i and j are
        
        
        #Just pay attention to this line
        print(str((i,j)))
        print('\n')

This is execution 1 of this print statememt
i is 0 and j is 0
(0, 0)


This is execution 2 of this print statememt
i is 0 and j is 1
(0, 1)


This is execution 3 of this print statememt
i is 0 and j is 2
(0, 2)


This is execution 4 of this print statememt
i is 1 and j is 0
(1, 0)


This is execution 5 of this print statememt
i is 1 and j is 1
(1, 1)


This is execution 6 of this print statememt
i is 1 and j is 2
(1, 2)




Think about why j increases first. Notice how this code gives you every permutation between the values (0,1) and (0,1,2). That is, (0,0) (0,1) (0,2) (1,0) (1,1) (1,2). Feel free to change the values of N and M to see you that changes the output.

7) Recall the `coords` in Question 4. After your modification, it consists of three pairs of distinct numbers: [1 2], [3 4] and [5 6].

In [9]:
print(r)

[array([1, 2]), array([3, 4]), array([5, 6])]


Now among the three pairs, we want to choose two of them. Use nested loop to print every possible result in such selection.

You anwer should look like:

Output 1: [1 2] [1 2]

Output 2: [1 2] [3 4]

Output 3: [1 2] [5 6]




Output 4: [3 4] [1 2]

Output 5: [3 4] [3 4]

Output 6: [3 4] [5 6]




Output 7: [5 6] [1 2]

Output 8: [5 6] [3 4]

Output 9: [5 6] [5 6]

In [10]:
coords[0]

array([1, 2])

In [11]:
# write your code here
for i in range(len(r)):
    for j in range(len(r)):
        print(r[i], r[j])

[1 2] [1 2]
[1 2] [3 4]
[1 2] [5 6]
[3 4] [1 2]
[3 4] [3 4]
[3 4] [5 6]
[5 6] [1 2]
[5 6] [3 4]
[5 6] [5 6]


When you run the cell below you should get a **Submit this notebook** button. Click that button, login, and your notebook should be recorded.

In [12]:
# do not change the code below
import comp116

comp116.submit('ws7')