# Assignment 4 Estimating Statistical Significance

**Due 8 November by 11:59:59PM **

This NASA post, <a href="http://www.nasa.gov/topics/earth/features/midweek_rainfall.html">NASA Data Link Pollution to Rainy Summer Days in the Southeast</a>, claims that in the southeastern US it rains more Tuesday through Thursday than it does Saturday through Monday. The presence of a seven-day cycle in the weather is "eerie" evidence that human activity influences the weather.

Your mission in this assignment is to see if you can validate their claim using data from the instruments at RDU airport. To quote from the article:

>Rainfall measurements collected from ground-based gauges can vary from one gauge site to the next because of fickle weather patterns. So, to identify any kind of significant weekly rainfall trend, Bell and colleagues looked at the big picture from Earth's orbit.

We are not really equipped to confirm or refute their claim but we're in the southeast, and have some data, let's see what we can do.

I have collected 10 years of data into a single file, `krdu-2001-2010.csv`, in a format suitable for use with np.loadtxt(). These data have 4 columns; year, month, day, and rainfall in inches.

First, you should read these posts by Allen Downey:

1. <a href="http://allendowney.blogspot.com/2011/05/there-is-only-one-test.html">There is only one test!</a>
2. <a href="http://allendowney.blogspot.com/2011/06/more-hypotheses-less-trivia.html">More hypotheses, less trivia.</a> Pay special attention to the paragraph <b>Permutation</b> under <b>Difference in means</b>. You shouldn't use his code; write your own.

## Learning objectives

The goal of this assignment is to give you more experience writing functions with loops and to expose you to an important use of computers in science.

## What to do

1. Read the data.
2. Determine the days of the week from the dates. (You can't just slice the array)
3. Write a function to get the average daily rainfall during midweek (Tuesday through Thursday) and weekend (Saturday through Monday).
4. Report the average rainfall for midweek and weekend, and their difference (delta). I provide a check for this so you can be sure you're on the right track.
5. Determine and report the p value (the likelihood that the effect is not real) by simulation. You'll need to first, compute the delta which in our case is the difference between the means for midweek and weekend. Then you'll run the function many times, each time permuting the day labels, and counting the number of times that the difference between the new means is greater than delta. Now divide that count by the number of trials you ran. That will be the p value. If count is 0, that means you didn't find even a single permutation that produced a greater difference in means; the effect is very likely real. On the other hand, if count is huge, then there were many permutations that produced greater differences, so the difference is likely just random.


## Tips

**1)** The <a href="https://docs.python.org/3.5/library/datetime.html#datetime.date.weekday"><b>weekday</b></a> method of the <b>date</b> class from the <b>datetime</b> module will be useful for getting the day of the week from the date. **Note:** The `weekday()` method returns `0` for Monday.

The date class knows nothing about numpy so you'll need to use a loop to process all the days. Also your data will be floats but the date function insists on ints; you'll need to use the int() function to convert them to int. 

You use it like this:


In [24]:
from datetime import date

# later in your code when you want to determine the day of the week
# you create a date object from a year, month, and day.
# I'll fake up a year, month, and day so we can see it work
year = 2000
month = 1
day = 1
do = date(year, month, day)
# and use its weekday method
day1 = do.weekday()

# or do it all in one step
day2 = date(year, month, day).weekday()

print(do, day1, day2)

2000-01-01 5 5


**2)** The <a href="http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.permutation.html"> `np.random.permutation`</a> function will be useful for permuting the data. You use it like this:

In [25]:
# first I'll create some array I want to shuffle.
import numpy as np
A = np.arange(10)
B = np.random.permutation(A)
B

array([7, 1, 5, 6, 4, 2, 3, 0, 9, 8])

**3)** You'll need to use a loop to run your simulation many times. I found that 1000 trials gives a faily stable result and doesn't require too long to run (good for debugging). Feel free to play with larger numbers but **I will time limit your submissions and assume they failed if they require more than 30 seconds to run on my computer**. 

**4)** I confirmed my intuition about how this should work by tweaking the data. For example, if I add 0.1 inches of rain to every Tuesday, the p value drops to zero (very significant) but if I replace the rainfall with random numbers it rises to near 0.5 (not significant at all).

## Checks

Since I'm not writing a lot of code for you, I can't give you the usual super structured checks.  I'm going to give you some very general ones to help keep you on track. You'll be responsible for making sure you put your various results into the correct variable names.

In [26]:
# fill in your onyen (not PID) here
Author = 'jcaldous'
Collaborators = []

In [27]:
# usual boilerplate
%matplotlib inline
import numpy as np
import pylab
from datetime import date
import comp116
check, report = comp116.start('A4')

## Read the data

First you should read the data. The delimiter is comma.

In [28]:
np.loadtxt('krdu-2001-2010.csv', delimiter=',')

array([[  2.00100000e+03,   1.00000000e+00,   1.00000000e+00,
          0.00000000e+00],
       [  2.00100000e+03,   1.00000000e+00,   2.00000000e+00,
          0.00000000e+00],
       [  2.00100000e+03,   1.00000000e+00,   3.00000000e+00,
          0.00000000e+00],
       ..., 
       [  2.01000000e+03,   1.20000000e+01,   2.90000000e+01,
          0.00000000e+00],
       [  2.01000000e+03,   1.20000000e+01,   3.00000000e+01,
          0.00000000e+00],
       [  2.01000000e+03,   1.20000000e+01,   3.10000000e+01,
          0.00000000e+00]])

In [29]:
# leave your result in data
data = np.loadtxt('krdu-2001-2010.csv', delimiter=',') # replace with your code

check('1: data', data, points=10)

1: data appears correct


In [30]:
data[25:36,:]

array([[  2.00100000e+03,   1.00000000e+00,   2.60000000e+01,
          0.00000000e+00],
       [  2.00100000e+03,   1.00000000e+00,   2.70000000e+01,
          0.00000000e+00],
       [  2.00100000e+03,   1.00000000e+00,   2.80000000e+01,
          0.00000000e+00],
       [  2.00100000e+03,   1.00000000e+00,   2.90000000e+01,
          0.00000000e+00],
       [  2.00100000e+03,   1.00000000e+00,   3.00000000e+01,
          3.11000000e-01],
       [  2.00100000e+03,   1.00000000e+00,   3.10000000e+01,
          0.00000000e+00],
       [  2.00100000e+03,   2.00000000e+00,   1.00000000e+00,
          0.00000000e+00],
       [  2.00100000e+03,   2.00000000e+00,   2.00000000e+00,
          0.00000000e+00],
       [  2.00100000e+03,   2.00000000e+00,   3.00000000e+00,
          0.00000000e+00],
       [  2.00100000e+03,   2.00000000e+00,   4.00000000e+00,
          2.08700000e-01],
       [  2.00100000e+03,   2.00000000e+00,   5.00000000e+00,
          9.84300000e-02]])

## Compute the day of the week

Then work out the day of the week for each date (0 is Monday)

In [31]:
r=[]
for i in range(len(data)):
    year= data[i,0]
    month= data[i,1]
    day= data[i,2]
    do = date(int(year), int(month), int(day))
    r.append(do.weekday())
np.array(r)

array([0, 1, 2, ..., 2, 3, 4])

In [32]:
# leave your result in dayOfWeek
r=[]
for i in range(len(data)):
    year= data[i,0]
    month= data[i,1]
    day= data[i,2]
    do = date(int(year), int(month), int(day))
    r.append(do.weekday())
dayOfWeek = np.array(r)
# put your code here

print(len(dayOfWeek), dayOfWeek)

check('2: days of week', dayOfWeek, points=20)

3652 [0 1 2 ..., 2 3 4]
2: days of week appears correct


## Compute rainfall amounts

Write a function that takes two arguments, an array of day numbers and
an array of rainfall amounts and returns the midweek and weekend rain as
defined by the NASA researchers. Remember you can return multiple results
by packing them into a tuple.

I **strongly recommend** using numpy array functions to group your days
into midweek and weekend; looping is likely to be too slow when you
call your function thousands of times in the next part.


In [33]:
midweek=0
n=7
for i in range(len(data)):
    if (dayOfWeek[i]==5)|(dayOfWeek[i]==6)|(dayOfWeek[i]==0):
        midweek= (midweek + data[i,3])
midweek

167.1517299999997

In [34]:
d= data[(dayOfWeek>=5)&(dayOfWeek<=6)|(dayOfWeek==0)]
f= d[:,3]
np.sum(f)

167.15172999999999

In [35]:
sumofend=np.sum(data[(dayOfWeek==5)|(dayOfWeek==6)|(dayOfWeek==0)], axis=0)
end=sumofend[3]/(len(data)/7)
end/3

0.10679646860167925

In [36]:
# Put the code for your function here
def rainfall(days, rain):
    WEEKEND=rain[(days==5)|(days==6)|(days==0)]
    SumWEEKEND= np.sum(WEEKEND, axis=0)
    MIDWEEK= rain[(days>=1)&(days<=3)]
    SumMIDWEEK=np.sum(MIDWEEK, axis=0)
    midwk1 = SumMIDWEEK[3]/len(MIDWEEK)
    wkend1 = SumWEEKEND[3]/len(WEEKEND)
    delta1 = midwk1 - wkend1
    return [midwk1,wkend1,delta1]
Function=rainfall(dayOfWeek,data)
midwk=Function[0]
wkend=Function[1]
delta=Function[2]
print('It rained', midwk, 'inches mid week')
print('It rained', wkend, 'inches weekend')
print('Difference was', delta, 'inches')

check('3: mid wk rain', midwk, points=15)
check('4: wk end rain', wkend, points=15)
check('5: difference', delta, points=15)


It rained 0.12604408046 inches mid week
It rained 0.106874507673 inches weekend
Difference was 0.0191695727871 inches
3: mid wk rain appears correct
4: wk end rain appears correct
5: difference appears correct


In [37]:
rainfall(dayOfWeek, data)

[0.12604408045976992, 0.10687450767263408, 0.019169572787135838]

## Test the null hypothesis

Finally test the null hypothesis that the day labeling is random
by running your function many times with different permutations of the days
and counting how many times the difference between the means is greater than the delta
you computed above.

In [38]:
np.random.seed(0)
m=np.random.permutation(data)
m

array([[  2.00600000e+03,   3.00000000e+00,   1.10000000e+01,
          1.18100000e-02],
       [  2.00200000e+03,   7.00000000e+00,   2.70000000e+01,
          1.18100000e-02],
       [  2.00400000e+03,   9.00000000e+00,   3.00000000e+01,
          0.00000000e+00],
       ..., 
       [  2.00500000e+03,   7.00000000e+00,   1.20000000e+01,
          0.00000000e+00],
       [  2.00800000e+03,   2.00000000e+00,   2.10000000e+01,
          1.18100000e-02],
       [  2.00800000e+03,   6.00000000e+00,   2.50000000e+01,
          0.00000000e+00]])

In [39]:
N = 10000  # number of trials, you can experiment with this
count = 0 # number of permutations that produced greater difference
np.random.seed(0)
for i in range(N):
    m=np.random.permutation(dayOfWeek)
    A=rainfall(m,data)
    dp=A[2]
    if dp>delta:
        count=count+1
p = count/N  # your code should compute the probability in this variable

# let's fix the starting point for random numbers to try to reduce the
# variability from run to run. Of course, in a real simulation you wouldn't
# do this but it should make grading easier.


# Write your code here

print('p =', p)

# Note: because of the randomness your answer may be quite different
# from the "expected" value below and still be correct. I have set
# the tolerance pretty wide.

check('6: p value', p, points=25, precision=1)

p = 0.0607
6: p value appears correct


## Results

100,000 reps gives me a p-value of 0.06 with about 55 seconds of computation. Not quite significant by the common standard of 0.05. As I said earlier, we don't have enough data to test the hypothesis; the NASA guys used the entire southeast. 

## Done!

Now get your report and submit your assignment.

In [40]:
report(Author, Collaborators)

1: data appears correct
2: days of week appears correct
3: mid wk rain appears correct
4: wk end rain appears correct
5: difference appears correct
6: p value appears correct
Report for jcaldous
  Collaborators: []
  6.0 of 6 possibly correct for up to 100.0 of 100 points
