# Midterm Exam 2

**Don't Panic!**

You **may not use the Internet** for anything except retrieving and submitting your exam. Any other use will be a violation of the Honor Code. 

You **must turn off wireless on your laptop** while you take the exam.

You **may use** any resources that you have stored locally on your computer or any paper notes, books, etc.

Of course you **may not** use phones, friends, etc.

Enter your **onyen** below.

In [2]:
Onyen = 'jcaldous'

## Honor Pledge

I certify that no unauthorized assistance has been received or given in the completion of this work. 

Enter your full name as the value of the Pledge variable below.

In [3]:
Pledge = 'Jessica Aldous'

## Data

You are given a dataset consisting of measured rainfall in inches at several station scattered across North Carolina for many consecutive days. There is a column for each station and a row for each day. That is, a 10 by 4 array represents 10 days with data at 4 stations for each day.

I am **not** telling you the number of stations or the number of days. You'll have to work those things out. Most importantly, you may **not assume** the dataset will be the same size when I do the grading. Your answer must work for any reasonable number of stations and days.

I'll load the data for you here. Don't change any of this.

In [4]:
%matplotlib inline
import numpy as np
import pylab
import comp116

check, report = comp116.start('Midterm2')
from comp116 import check_function

rain = np.loadtxt('rain.txt')
rain.setflags(write=False) # don't allow writing the array

Here are the first few rows of the rain data. Remember it may have a different number of rows and columns when I grade it.

In [5]:
rain[:5]

array([[ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.03,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.16,  0.28,  0.  ,  0.83,  0.  ],
       [ 2.22,  0.03,  0.  ,  0.01,  0.  ],
       [ 0.03,  0.02,  0.87,  0.  ,  0.  ]])

## 1. How many days had 0 rain at all stations?

Write a function F1 that takes an array like the one above as its only argument and returns the number of days.

In [6]:
# define your function F1 here. My checking code will call it for you.
def F1(data):
    count=0
    for i in range(len(data)):
        if np.all(data[i]==0):
            count=count+1
    return count
# Let's see what your function returns
Q1 = F1(rain)
print('F1 result')
print(Q1)

check_function('F1', F1, rain, points=15)

F1 result
34
F1 appears correct


## 2. Which day had the greatest difference between the maximum and minimum rainfall?

Write a function F2 that takes an array like the one above as its only argument and returns the index of the day.

In [7]:
np.argmax(np.max(rain[1])-np.min(rain[1]))

0

In [8]:
# define your function F2 here. My checking code will call it for you.
def F2(data):
    r=[]
    for i in range(len(data)):
        r.append(np.max(data[i])-np.min(data[i]))
    return np.argmax(r) 
# Let's see what your function returns
Q2 = F2(rain)
print('F2 result')
print(Q2)

check_function('F2', F2, rain, points=20)

F2 result
3
F2 appears correct


## 3. What was the longest run of days where at least one station had less than R inches of rain?

Write a function F3 that takes two arguments, an array like the one above and a float giving the amount of rain. It should return the length of the longest run of consecutive days where the rain for at least one of the stations was less than R.

For example, F3(rain, 0.1) would return an integer giving the length of the longest run of days where the rainfall for at least one station was less than 0.1 inches.

In [9]:
#template
def F3(data):
    station_count=np.zeros(np.shape(data)[1])
    for i in range(len(data)):
        if np.any(data[i,:]!=0):
            highest=np.argmax(data[i,:])
            station_count[highest]= station_count[highest]+1
    return np.argmax(station_count)+1
F3(rain)

1

In [10]:
# define your function F3 here. My checking code will call it for you.
def F3(data, R):
    count=0
    max_count=0
    for i in range(len(data)):
        if np.any(data[i]<R):
            count=count+1
        else:
            count=0
        if count> max_count:
            max_count=count
    return max_count
# Let's see what your function returns
Q3 = F3(rain, 0.02)
print('F3 result')
print(Q3)

check_function('F3', F3, rain, 0.03, points=20)

F3 result
32
F3 appears correct


## 4. For each station, how many days had more rain than the previous day?

Write a function F4 that takes an array like the one above as its only argument and returns a list with the number of days for each station where the rainfall was greater than the day before.

In [11]:
station_count=np.zeros(np.shape(rain)[1])
np.int_(station_count)

array([0, 0, 0, 0, 0])

In [12]:
np.count_nonzero(rain[1:,:]>rain[0:-1,:], axis=0)

array([42, 28, 37, 41, 32])

In [13]:
def F4(data):
    r=[]
    station_count=np.zeros(np.shape(data)[1])
    for i in range(1,len(data)):
        for n in range(len(station_count)):
            if np.any(data[i,n]>data[i-1,n]):
                station_count[n]= station_count[n]+1
    return station_count

# Let's see what your function returns
Q4 = F4(rain)
print('F4 result')
print(Q4)

check_function('F4', F4, rain, points=20)

F4 result
[ 42.  28.  37.  41.  32.]
F4 incorrect type
your answer type is array of 5 floats
expected type is list of 5 integers


## 5. Which station had the longest run of days with no rain?

Write a function F5 that takes an array like the one above as its only argument and returns the index of the station (column).

In [14]:
def F5(data):
    station_count=np.zeros(np.shape(data)[1])
    r=np.zeros(np.shape(data)[1])
    for i in range(len(data)):
        for n in range(len(station_count)):
            if (data[i,n]==0):
                station_count[n]= station_count[n]+1
            else:
                station_count[n]=0
            if station_count[n]>r[n]:
                r[n]=station_count[n]
    return np.argmax(r)
# Let's see what your function returns
Q5 = F5(rain)
print('F5 result')
print(Q5)

check_function('F5', F5, rain, points=25)

F5 result
4
F5 appears correct


## Done!

Now go back, restart the kernel (Kernel menu -> Restart), and then Shift-Enter your way through the notebook to run all the cells again so you an be sure all your code will work as you expect during grading.

In [15]:
# Do NOT modify this
report(Onyen, Pledge)

F1 appears correct
F2 appears correct
F3 appears correct
F4 incorrect
F5 appears correct
Report for jcaldous
  Pledged on my honor: Jessica Aldous
    jcaldous
  4.0 of 5 possibly correct for up to 80.0 of 100 points


# You MUST scan your one-card before you leave the room