# Notes 13 September

## Homework helps

In [2]:
%matplotlib inline
import numpy as np
import pylab

In [3]:
A = np.array([3, 5, 7, 9, 11, 13])

In [4]:
A

array([ 3,  5,  7,  9, 11, 13])

Let's look at the difference between reshaping 2, 3 and 3, 2. Note the values step left to right, top to bottom in either case.

In [5]:
np.reshape(A, (2, 3))

array([[ 3,  5,  7],
       [ 9, 11, 13]])

In [6]:
np.reshape(A, (3, 2))

array([[ 3,  5],
       [ 7,  9],
       [11, 13]])

Difference between count_nonzero and length. An array full of zeros.

In [7]:
Z = np.zeros(10)

In [8]:
Z

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

It's length is 10.

In [9]:
len(Z)

10

But count_nonzero returns 0. Because there are NO nonzero values.

In [10]:
np.count_nonzero(Z)

0

In [11]:
A32 = np.reshape(A, (3, 2))

In [12]:
A32

array([[ 3,  5],
       [ 7,  9],
       [11, 13]])

In [13]:
A32[-1,:]

array([11, 13])

In [14]:
A32[:,0]

array([ 3,  7, 11])

In [15]:
A32[:,0] > 3

array([False,  True,  True], dtype=bool)

In [16]:
np.sum(A32[:,0] > 3)

2

In [17]:
np.count_nonzero(A32[:,0] > 3)

2

In [18]:
np.count_nonzero(~(A32[:,0] > 3))

1

In [19]:
~np.count_nonzero(A32[:,0] > 3)

-3