# Notes for 27 October


In [1]:
%matplotlib inline
import numpy as np
import pylab

In [2]:
dates = np.array([[2017, 10, 1], [2017, 10, 2], [2017, 10, 13], [2017, 10, 27.0]])
dates

array([[  2.01700000e+03,   1.00000000e+01,   1.00000000e+00],
       [  2.01700000e+03,   1.00000000e+01,   2.00000000e+00],
       [  2.01700000e+03,   1.00000000e+01,   1.30000000e+01],
       [  2.01700000e+03,   1.00000000e+01,   2.70000000e+01]])

In [11]:
from datetime import date

dow = []
for i in range(len(dates)):
    d = date(int(dates[i,0]), int(dates[i,1]), int(dates[i,2]))
    dow.append(d.weekday())
dow = np.array(dow)
dow   

array([6, 0, 4, 4])

In [9]:
dow = np.zeros(len(dates))
for i in range(len(dates)):
    d = date(int(dates[i,0]), int(dates[i,1]), int(dates[i,2]))
    dow[i] = d.weekday()
dow

array([ 6.,  0.,  4.,  4.])

Fake up some day of week numbers.

In [15]:
dow = np.arange(30) % 7
dow

array([0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1,
       2, 3, 4, 5, 6, 0, 1])

Fake up some rainfall for those days

In [14]:
rainfall = np.random.random(30)
rainfall

array([ 0.37901477,  0.19523855,  0.36257363,  0.4570576 ,  0.66102895,
        0.20983061,  0.62204543,  0.08847247,  0.52073284,  0.83671967,
        0.0732689 ,  0.2307887 ,  0.65217536,  0.79023559,  0.20393336,
        0.68320818,  0.00215701,  0.89647913,  0.34038861,  0.79459435,
        0.76653122,  0.06276035,  0.8249358 ,  0.45781516,  0.56254324,
        0.54257566,  0.0988149 ,  0.95989629,  0.60341921,  0.15754205])

What was the total rainfall on Sunday?

In [16]:
t = 0
for i in range(len(dow)):
    if dow[i] == 6:
        t = t + rainfall[i]
print(t)

3.13870853479


In [17]:
np.sum(rainfall[dow == 6])

3.1387085347944295

In [18]:
dow == 6

array([False, False, False, False, False, False,  True, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
        True, False, False], dtype=bool)

In [19]:
np.sum(rainfall[(dow == 6) | (dow == 5)])

4.8941237454675726

In [20]:
np.sum(rainfall[(dow >= 1) & (dow <= 3)])

6.030271770921761

In [21]:
np.random.permutation(dow)

array([1, 2, 3, 0, 0, 6, 2, 5, 6, 2, 4, 1, 1, 6, 1, 0, 3, 1, 5, 0, 4, 3, 6,
       4, 3, 5, 5, 4, 2, 0])