# Notes for 15 November

Today we'll look at various ways to solve the problems on the midterm.

In [1]:
%matplotlib inline
import numpy as np
import pylab

In [2]:
rain = np.array([
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.03,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.16,  0.28,  0.  ,  0.83,  0.  ],
       [ 2.22,  0.03,  0.  ,  0.01,  0.  ],
       [ 0.03,  0.02,  0.87,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.01,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.19,  0.86,  0.  ,  1.09,  0.  ],
       [ 0.54,  0.35,  1.73,  0.02,  0.  ],
       [ 0.04,  0.04,  0.86,  0.07,  0.  ],
       [ 0.02,  0.  ,  0.02,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.02,  0.39,  0.  ,  0.55,  0.  ],
       [ 0.  ,  0.04,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.27,  0.  ,  0.  ,  0.29,  0.  ],
       [ 0.61,  0.78,  1.88,  1.71,  0.  ],
       [ 0.04,  0.  ,  0.38,  0.  ,  0.  ],
       [ 0.  ,  0.07,  0.  ,  0.  ,  0.  ],
       [ 0.04,  0.02,  0.02,  0.03,  0.  ],
       [ 0.  ,  0.  ,  0.02,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.01,  0.  ],
       [ 0.  ,  0.  ,  0.02,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.11,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.49,  0.23,  0.31,  0.91,  0.43],
       [ 0.  ,  0.03,  0.35,  0.  ,  0.49],
       [ 0.  ,  0.  ,  0.  ,  0.08,  0.  ],
       [ 0.  ,  0.  ,  1.  ,  1.56,  1.73],
       [ 0.  ,  0.  ,  0.02,  0.  ,  0.04],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.28,  0.  ,  0.02,  0.  ,  0.  ],
       [ 0.19,  0.96,  0.16,  0.74,  0.3 ],
       [ 0.  ,  0.02,  0.31,  0.  ,  0.43],
       [ 0.  ,  0.  ,  0.01,  0.01,  0.  ],
       [ 0.  ,  0.  ,  0.02,  0.  ,  0.03],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.14,  0.  ],
       [ 1.32,  0.19,  1.08,  0.85,  1.06],
       [ 0.  ,  0.  ,  0.01,  0.02,  0.  ],
       [ 0.05,  0.  ,  0.  ,  0.  ,  0.03],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.06,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.65,  0.31,  0.13,  0.59,  0.32],
       [ 0.02,  0.  ,  0.12,  0.6 ,  0.49],
       [ 0.  ,  0.  ,  0.11,  0.6 ,  0.  ],
       [ 0.04,  0.12,  0.13,  0.27,  0.49],
       [ 0.48,  0.74,  1.3 ,  0.97,  1.21],
       [ 0.  ,  0.02,  0.02,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.05,  0.  ,  0.05,  0.  ],
       [ 0.16,  0.43,  0.17,  0.  ,  0.04],
       [ 0.06,  0.  ,  0.01,  0.01,  0.  ],
       [ 0.43,  0.19,  0.03,  0.01,  0.  ],
       [ 0.62,  0.13,  0.  ,  0.24,  0.  ],
       [ 0.29,  0.49,  0.49,  0.01,  0.25],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.01],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.12,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.18,  0.15,  0.  ,  0.  ,  0.  ],
       [ 0.23,  0.  ,  0.  ,  0.03,  0.  ],
       [ 0.58,  0.  ,  0.21,  0.12,  0.12],
       [ 0.03,  0.  ,  0.  ,  0.03,  0.  ],
       [ 0.03,  0.19,  0.15,  0.49,  0.08],
       [ 0.02,  0.37,  1.28,  0.  ,  0.52],
       [ 0.  ,  0.  ,  0.01,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.07,  0.  ,  0.  ,  0.08,  0.  ],
       [ 0.14,  0.73,  0.13,  1.18,  0.13],
       [ 0.08,  0.  ,  0.19,  0.  ,  0.62],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.01],
       [ 0.54,  0.  ,  0.  ,  0.06,  0.06],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.61,  0.02,  0.01,  0.  ],
       [ 0.31,  0.  ,  0.14,  0.18,  0.05],
       [ 0.  ,  0.39,  0.48,  0.  ,  0.14],
       [ 0.  ,  0.  ,  0.01,  0.  ,  0.  ],
       [ 0.68,  0.  ,  0.  ,  0.05,  0.  ],
       [ 0.  ,  0.  ,  0.15,  0.  ,  0.05],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.21,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 1.34,  0.  ,  0.  ,  0.47,  0.  ],
       [ 0.  ,  0.  ,  0.07,  0.  ,  0.68],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.51,  0.01,  0.  ,  0.  ,  0.  ],
       [ 0.04,  0.51,  0.02,  0.  ,  0.  ],
       [ 0.  ,  0.39,  0.45,  0.25,  0.  ],
       [ 0.12,  0.22,  0.  ,  0.  ,  0.  ],
       [ 0.31,  0.  ,  0.19,  0.34,  0.37],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.04],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.26,  0.01,  0.  ,  0.61,  0.  ],
       [ 0.36,  0.27,  0.73,  0.  ,  1.  ],
       [ 0.43,  0.16,  0.02,  0.  ,  0.01],
       [ 0.53,  0.08,  0.  ,  0.  ,  0.  ],
       [ 0.28,  0.02,  0.  ,  0.  ,  0.  ],
       [ 0.52,  0.  ,  0.  ,  0.04,  0.  ],
       [ 0.63,  0.94,  0.67,  0.04,  0.13],
       [ 0.  ,  0.03,  0.01,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.07,  0.  ],
       [ 0.  ,  0.11,  0.2 ,  0.09,  0.06],
       [ 0.  ,  0.03,  0.06,  0.  ,  0.15],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.01,  0.  ],
       [ 0.07,  0.52,  0.38,  0.14,  0.  ],
       [ 0.  ,  0.  ,  0.12,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.06],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.15],
       [ 0.  ,  0.  ,  0.  ,  0.01,  0.  ],
       [ 0.57,  0.  ,  0.  ,  0.58,  0.61]])

In [4]:
def MaxRunLength(P):
    result = 0
    N = 0
    for i in range(len(P)):
        if P[i]:
            N = N + 1
        else:
            N = 0
        if N > result:
            result = N
    return result

A randomly selected wrong answer. Let's see how we can transform it.

Which station had the longest run of days with no rain?

In [6]:
def F5(data):
    count = []
    for j in range(len(data[1])):
        count.append(MaxRunLength(data[:,j] == 0))
        
    return np.argmax(count)
F5(rain)

4

Here is a solution I came up with

In [5]:
def F5(A):
    isDry = A == 0
    counts = []
    for i in range(A.shape[1]): # for each column
        counts.append(MaxRunLength(isDry[:,i]))
    return np.argmax(counts)

F5(rain)


4

Here is another incorrect solution

In [7]:
def F5(data):
    result=0
    maxindex= 0 
    N=0
    for i in range(len(data)): #visit all of the values in the sequence
        if (data[i]==0): #if P[i](true) == true: I am going to increment to value of N, it becomes 1 
            N = N + 1
        else:
            N = 0
        if N> result:
            result = N
            maxindex = i
    return result, maxindex
F5(rain)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [9]:
def F5(data):
    runs = []
    for j in range(data.shape[1]): # for each column
        result=0
        N=0
        for i in range(len(data)): #visit all of the values in the sequence
            if (data[i,j]==0): #if P[i](true) == true: I am going to increment to value of N, it becomes 1 
                N = N + 1
            else:
                N = 0
            if N> result:
                result = N
        runs.append(result)
    return np.argmax(runs)
F5(rain)

4

And another.

For each station, how many days had more rain than the previous day?

In [ ]:
def F4 (data):
    count = 0
    r = []
    for i in range(len(data)):
        if data[i-1] < data[i]:
            count = count + data[i]
            r.append(count)
        
    return np.max(r) 


In [10]:
def F4 (data):
    return np.count_nonzero(data[1:] > data[0:-1], axis=0)
F4(rain)

array([42, 28, 37, 41, 32])

In [11]:
def F4 (data):
    r = []
    for j in range(data.shape[1]): # for each station
        count = 0
        for i in range(1, len(data)): # for each day
            if data[i-1, j] < data[i, j]:
                count = count + 1
        r.append(count)
        
    return r
F4(rain)


[42, 28, 37, 41, 32]

In [14]:
def F4 (data):
    count = 0
    for i in range(1,len(data)):
        count = count + (data[i-1] < data[i])
        
    return count
F4(rain)

array([42, 28, 37, 41, 32])

In [15]:
def F4(data):
    counts = np.zeros(data.shape[1], dtype=int)
    for i in range(1, len(data)):
        for j in range(data.shape[1]):
            if data[i, j] > data[i-1, j]:
                counts[j] = counts[j] + 1
    return counts
F4(rain)

array([42, 28, 37, 41, 32])

In [16]:
def F4(data):
    counts = np.zeros(data.shape[1], dtype=int)
    for j in range(data.shape[1]):
        for i in range(1, len(data)):
            if data[i, j] > data[i-1, j]:
                counts[j] = counts[j] + 1
    return counts
F4(rain)

array([42, 28, 37, 41, 32])

In [17]:
def F3(data, R):
    result = 0
    N = 0
    for i in range(len(data)):
        if np.any(data[i] < R):
            N = N + 1
        else:
            N = 0
        if N > result:
            result = N
    return result
F3(rain, 0.2)

71

This is a completely crazy version of F5 that came to me. You should not write code like this.

In [7]:
def F5crazy(data):
    count = 0
    longest = 0
    for i in range(len(data)):
        t = (data[i] == 0)
        count = (count + t) * t
        longest = np.maximum(longest, count)
        print(count, longest)
    return np.argmax(longest)
F5crazy(rain)

[1 1 1 1 1] [1 1 1 1 1]
[0 2 2 2 2] [1 2 2 2 2]
[0 0 3 0 3] [1 2 3 2 3]
[0 0 4 0 4] [1 2 4 2 4]
[0 0 0 1 5] [1 2 4 2 5]
[1 1 0 2 6] [1 2 4 2 6]
[2 2 1 3 7] [2 2 4 3 7]
[3 3 2 4 8] [3 3 4 4 8]
[4 4 3 5 9] [4 4 4 5 9]
[ 5  5  4  6 10] [ 5  5  4  6 10]
[ 6  6  5  7 11] [ 6  6  5  7 11]
[ 0  0  6  0 12] [ 6  6  6  7 12]
[ 0  0  0  0 13] [ 6  6  6  7 13]
[ 0  0  0  0 14] [ 6  6  6  7 14]
[ 0  1  0  1 15] [ 6  6  6  7 15]
[ 1  2  1  2 16] [ 6  6  6  7 16]
[ 2  3  2  3 17] [ 6  6  6  7 17]
[ 0  0  3  0 18] [ 6  6  6  7 18]
[ 1  0  4  1 19] [ 6  6  6  7 19]
[ 2  1  5  2 20] [ 6  6  6  7 20]
[ 3  2  6  3 21] [ 6  6  6  7 21]
[ 4  3  7  4 22] [ 6  6  7  7 22]
[ 0  4  8  0 23] [ 6  6  8  7 23]
[ 0  0  0  0 24] [ 6  6  8  7 24]
[ 0  1  0  1 25] [ 6  6  8  7 25]
[ 1  0  1  2 26] [ 6  6  8  7 26]
[ 0  0  0  0 27] [ 6  6  8  7 27]
[ 1  1  0  1 28] [ 6  6  8  7 28]
[ 2  2  1  0 29] [ 6  6  8  7 29]
[ 3  3  0  1 30] [ 6  6  8  7 30]
[ 4  4  0  2 31] [ 6  6  8  7 31]
[ 5  5  1  3 32] [ 6  6  8  7 32]
[0

4