# Notes for 6 December



In [1]:
%matplotlib inline
import numpy as np
import pylab

In [2]:
import urllib.request
urllib.request.urlretrieve('https://cs.unc.edu/Courses/comp116-f17/media/fedata.npz', 'fedata.npz')

('fedata.npz', <http.client.HTTPMessage at 0x7f6fa19512e8>)

In [3]:
with np.load('fedata.npz') as data:
    BigNames = list(data['names'])
    BigYears = data['years']
    BigPopulations = data['populations']

In [4]:
BN = BigNames
BY = BigYears
BP = BigPopulations

In [5]:
TN = BigNames[:5]
TY = BY[:6]
TP = BP[:6,:5]
TP

array([[  3.20276380e+02,   5.47300000e-02,   2.83698000e+01,
          9.37869900e+01,   3.47570000e-01],
       [  3.24446940e+02,   5.49100000e-02,   2.88480600e+01,
          9.76191500e+01,   3.63430000e-01],
       [  3.28620140e+02,   5.51700000e-02,   2.93298800e+01,
          1.01522510e+02,   3.77960000e-01],
       [  3.32724870e+02,   5.55100000e-02,   2.97935500e+01,
          1.05530110e+02,   3.93030000e-01],
       [  3.36721430e+02,   5.58500000e-02,   3.02306400e+01,
          1.09623520e+02,   4.08300000e-01],
       [  3.40748110e+02,   5.61800000e-02,   3.06717600e+01,
          1.13892030e+02,   4.23990000e-01]])

In [6]:
TN

['North America', 'Bermuda', 'Argentina', 'Middle East', 'Bahrain']

In [7]:
TY

array([1980, 1981, 1982, 1983, 1984, 1985])

In [8]:
def RC(Names, Years, Populations):
    return (Populations[1:,:] - Populations[0:-1,:]) / Populations[0:-1,:]
RC(TN, TY, TP)

array([[ 0.01302175,  0.00328887,  0.01685807,  0.04086025,  0.0456311 ],
       [ 0.0128625 ,  0.00473502,  0.01670199,  0.0399856 ,  0.03998019],
       [ 0.0124908 ,  0.00616277,  0.01580879,  0.03947499,  0.03987194],
       [ 0.01201161,  0.00612502,  0.01467063,  0.03878902,  0.038852  ],
       [ 0.01195849,  0.00590868,  0.01459182,  0.0389379 ,  0.03842763]])

In [10]:
def RC2(Names, Years, Populations):
    return np.diff(Populations, axis=0) / Populations[0:-1,:]
rc = RC2(TN, TY, TP)

In [11]:
V = rc[0,0]
V

0.013021753274468832

In [12]:
rc == V

array([[ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]], dtype=bool)

In [16]:
bv = np.any(rc == V, axis=1)
bv

array([ True, False, False, False, False], dtype=bool)

In [14]:
def RC3(Names, Years, Populations):
    Result = np.zeros([len(Years)-1, len(Names)])
    for y in range(1, len(Years)):
        for n in range(len(Names)):
            Result[y-1,n] = (Populations[y,n] - Populations[y-1,n]) / Populations[y-1,n]
    return Result
RC3(TN, TY, TP)

array([[ 0.01302175,  0.00328887,  0.01685807,  0.04086025,  0.0456311 ],
       [ 0.0128625 ,  0.00473502,  0.01670199,  0.0399856 ,  0.03998019],
       [ 0.0124908 ,  0.00616277,  0.01580879,  0.03947499,  0.03987194],
       [ 0.01201161,  0.00612502,  0.01467063,  0.03878902,  0.038852  ],
       [ 0.01195849,  0.00590868,  0.01459182,  0.0389379 ,  0.03842763]])

In [15]:
def RC4(Names, Years, Populations):
    Result = np.zeros([len(Years)-1, len(Names)])
    for y in range(len(Years)-1):
        for n in range(len(Names)):
            Result[y,n] = (Populations[y+1,n] - Populations[y,n]) / Populations[y,n]
    return Result
RC4(TN, TY, TP)

array([[ 0.01302175,  0.00328887,  0.01685807,  0.04086025,  0.0456311 ],
       [ 0.0128625 ,  0.00473502,  0.01670199,  0.0399856 ,  0.03998019],
       [ 0.0124908 ,  0.00616277,  0.01580879,  0.03947499,  0.03987194],
       [ 0.01201161,  0.00612502,  0.01467063,  0.03878902,  0.038852  ],
       [ 0.01195849,  0.00590868,  0.01459182,  0.0389379 ,  0.03842763]])

In [17]:
TY[1:]

array([1981, 1982, 1983, 1984, 1985])

In [18]:
TY[1:][bv]

array([1981])