# Exercise with Arrays

Today we'll review and practice with the array operations we have learned.

First we'll do our usual setup and fake up some simple data.

In [1]:
%matplotlib inline
import numpy as np
import pylab

Let's pretend we are repeatedly rolling five different 6-sided dice. The call to `randint` below says I want pseudo-random integers (whole numbers) in the range from 1 up to but not including 7. The third argument is the shape I want. Here I am asking for 10 rows of 5 columns.

In [2]:
np.random.seed(0) # not usually done irl unless you're debugging
D = np.random.randint(1, 7, (10, 5))
D

array([[5, 6, 1, 4, 4],
       [4, 2, 4, 6, 3],
       [5, 1, 1, 5, 3],
       [2, 1, 2, 6, 2],
       [6, 1, 2, 5, 4],
       [1, 4, 6, 1, 3],
       [4, 1, 2, 4, 6],
       [4, 4, 1, 2, 2],
       [2, 1, 3, 5, 4],
       [4, 3, 5, 3, 1]])

Were any of the rolls greater than 3?

In [21]:
np.any(D > 3)

True

For each column were there any values greater than 5?

In [22]:
np.any(D > 5, axis=0)

array([ True,  True,  True,  True,  True], dtype=bool)

For each column were there any values equal to 5?

In [23]:
np.any(D == 5, axis=0)

array([ True, False,  True,  True, False], dtype=bool)

For each row, were there any values equal to 5?

In [24]:
np.any(D == 5, axis=1)

array([ True, False,  True, False,  True, False, False, False,  True,  True], dtype=bool)

How many rows had at least one value equal to 5?

In [26]:
np.sum(np.any(D == 5, axis=1))

5

Sum of the array isn't that interesting. I was answering a question about the difference between summing D and suming the comparison.

In [27]:
np.sum(D)

161

How about inverting the condition? We can use the tilde character to invert booleans.

In [28]:
~np.any(D == 5, axis=1)

array([False,  True, False,  True, False,  True,  True,  True, False, False], dtype=bool)

Last row all of the columns

In [29]:
D[-1,:]

array([4, 3, 5, 3, 1])

Also last row but I like the explicit version above better.

In [30]:
D[-1]

array([4, 3, 5, 3, 1])

In [31]:
D[-1,:]

array([4, 3, 5, 3, 1])

First row, last two columns

In [32]:
D[0,-2:]

array([4, 4])

len applied to an array gives us the first dimension.

In [33]:
len(D)

10

shape shows us all of the dimensions.

In [35]:
D.shape

(10, 5)

We could get the number of columns by asking for the length of a row

In [37]:
len(D[0])

5

But it is better to index into the shape. 0 gives me the first (row) dimension.

In [38]:
D.shape[0]

10

1 gives me the second (columns) dimension.

In [39]:
D.shape[1]

5

We could get the last row without using negative numbers.

In [40]:
D[len(D)-1, :]

array([4, 3, 5, 3, 1])

First two rows, first column

In [41]:
D[:2,0]

array([5, 4])

We can transpose an array to swap the rows and columns.

In [42]:
D.T

array([[5, 4, 5, 2, 6, 1, 4, 4, 2, 4],
       [6, 2, 1, 1, 1, 4, 1, 4, 1, 3],
       [1, 4, 1, 2, 2, 6, 2, 1, 3, 5],
       [4, 6, 5, 6, 5, 1, 4, 2, 5, 3],
       [4, 3, 3, 2, 4, 3, 6, 2, 4, 1]])

Last row backward in answer to a question.

In [44]:
D[-1, ::-1]

array([1, 3, 5, 3, 4])

Note the order of the values isn't the same as the transpose.

In [45]:
np.reshape(D, (5,10))

array([[5, 6, 1, 4, 4, 4, 2, 4, 6, 3],
       [5, 1, 1, 5, 3, 2, 1, 2, 6, 2],
       [6, 1, 2, 5, 4, 1, 4, 6, 1, 3],
       [4, 1, 2, 4, 6, 4, 4, 1, 2, 2],
       [2, 1, 3, 5, 4, 4, 3, 5, 3, 1]])

In [46]:
D

array([[5, 6, 1, 4, 4],
       [4, 2, 4, 6, 3],
       [5, 1, 1, 5, 3],
       [2, 1, 2, 6, 2],
       [6, 1, 2, 5, 4],
       [1, 4, 6, 1, 3],
       [4, 1, 2, 4, 6],
       [4, 4, 1, 2, 2],
       [2, 1, 3, 5, 4],
       [4, 3, 5, 3, 1]])

All rows, first 3 columns.

In [47]:
D[:,:3]

array([[5, 6, 1],
       [4, 2, 4],
       [5, 1, 1],
       [2, 1, 2],
       [6, 1, 2],
       [1, 4, 6],
       [4, 1, 2],
       [4, 4, 1],
       [2, 1, 3],
       [4, 3, 5]])

Rows 4, 5, 6 columns 1,2,3

In [48]:
D[4:7, 1:4]

array([[1, 2, 5],
       [4, 6, 1],
       [1, 2, 4]])

Count the number of 1's in that block.

In [51]:
np.count_nonzero(D[4:7, 1:4] == 1)

3

In [52]:
m0 = np.min(D[:,0])
m1 = np.min(D[:,1])
m2 = np.min(D[:,2])
m3 = np.min(D[:,3])
m4 = np.min(D[:,4])
C0 = D[:,0] - m0
C1 = D[:,1] - m1


Get the minimum of each column.

In [53]:
np.min(D, axis=0)

array([1, 1, 1, 1, 1])

Subtract off the minimum (like the problem in A1)

In [54]:
D - np.min(D, axis=0)

array([[4, 5, 0, 3, 3],
       [3, 1, 3, 5, 2],
       [4, 0, 0, 4, 2],
       [1, 0, 1, 5, 1],
       [5, 0, 1, 4, 3],
       [0, 3, 5, 0, 2],
       [3, 0, 1, 3, 5],
       [3, 3, 0, 1, 1],
       [1, 0, 2, 4, 3],
       [3, 2, 4, 2, 0]])