# Notes for 25 September - review

In [1]:
%matplotlib inline
import numpy as np
import pylab

Some fake data similar in form to the exam.

In [9]:
np.random.seed(0)
data = np.random.randint(0, 100, (14,5))
data

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72],
       [ 9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88],
       [49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57],
       [32, 31, 74, 23, 35],
       [75, 55, 28, 34,  0],
       [ 0, 36, 53,  5, 38],
       [17, 79,  4, 42, 58],
       [31,  1, 65, 41, 57]])

A question about finding the index of all of the True values in an array.

In [3]:
b = np.array([0,1,0,0,1], dtype=bool)
b

array([False,  True, False, False,  True], dtype=bool)

Make an array of index values

In [10]:
i = np.arange(len(b))
i

array([0, 1, 2, 3, 4])

Use boolean selection to extract the indexes of the True values

In [11]:
i[b]

array([1, 4])

A question about finding the weights that were greater than the mean weight. First we faked up some data.

In [12]:
w = np.array([3,5,8,2,6,6,2])
w

array([3, 5, 8, 2, 6, 6, 2])

Then we got the mean

In [13]:
np.mean(w)

4.5714285714285712

Compare the weights to the mean

In [14]:
w > np.mean(w)

array([False,  True,  True, False,  True,  True, False], dtype=bool)

Use boolean selection of choose the weights that are greater than the mean.

In [15]:
w [ w > np.mean(w) ]

array([5, 8, 6, 6])

Get the mean of those.

In [16]:
np.mean(w [ w > np.mean(w) ])

6.25

Or breaking it down into little steps. First get the mean.

In [17]:
mw = np.mean(w)
mw

4.5714285714285712

Then get the vector of compares.

In [18]:
isbigger = w > mw
isbigger

array([False,  True,  True, False,  True,  True, False], dtype=bool)

Then get the weights corresponding to True

In [19]:
bigones = w [ isbigger ]
bigones

array([5, 8, 6, 6])

Then get the mean of those.

In [20]:
np.mean(bigones)

6.25

A question about 3d arrays. 

In [21]:
np.random.seed(3)
a3d = np.random.randint(0, 100, (2, 3, 4))
a3d

array([[[24,  3, 56, 72],
        [ 0, 21, 19, 74],
        [41, 10, 21, 38]],

       [[96, 20, 44, 93],
        [39, 14, 26, 81],
        [90, 22, 66,  2]]])

The first plane, all the rows, and columns.

In [22]:
a3d[0]

array([[24,  3, 56, 72],
       [ 0, 21, 19, 74],
       [41, 10, 21, 38]])

In [ ]:
Choosing only the first row of each.

In [23]:
a3d[:,0,:]

array([[24,  3, 56, 72],
       [96, 20, 44, 93]])

Choosing only the first column of each.

In [24]:
a3d[:,:,0]

array([[24,  0, 41],
       [96, 39, 90]])

A question about reshaping data into a 3D array. We used the array I created above and made into week-sized chunks.

In [25]:
dataWeekly = np.reshape(data, (-1,7,5))
dataWeekly

array([[[44, 47, 64, 67, 67],
        [ 9, 83, 21, 36, 87],
        [70, 88, 88, 12, 58],
        [65, 39, 87, 46, 88],
        [81, 37, 25, 77, 72],
        [ 9, 20, 80, 69, 79],
        [47, 64, 82, 99, 88]],

       [[49, 29, 19, 19, 14],
        [39, 32, 65,  9, 57],
        [32, 31, 74, 23, 35],
        [75, 55, 28, 34,  0],
        [ 0, 36, 53,  5, 38],
        [17, 79,  4, 42, 58],
        [31,  1, 65, 41, 57]]])

Axis 0 will eliminate the "week number" dimension. Leaving us with totals per week day.

In [26]:
np.sum(dataWeekly, axis=0)

array([[ 93,  76,  83,  86,  81],
       [ 48, 115,  86,  45, 144],
       [102, 119, 162,  35,  93],
       [140,  94, 115,  80,  88],
       [ 81,  73,  78,  82, 110],
       [ 26,  99,  84, 111, 137],
       [ 78,  65, 147, 140, 145]])

Axis 1 will eliminate the weekday dimension. Now we've got weekly totals.

In [27]:
np.sum(dataWeekly, axis=1)

array([[325, 378, 447, 406, 539],
       [243, 263, 308, 173, 259]])

In response to a question we realized we could sum over two dimensions simultaneously. Cool! This is giving us the total for each column.

In [30]:
np.sum(dataWeekly, axis=(0,1))

array([568, 641, 755, 579, 798])

We talked a bit about the "distance" calculations that will be used to determine partial credit.

The distance is measured in "symbols". A complete identifier is one symbol, the length of the identifier doesn't matter. 

Here is a little table summarizing the discussion.

<table>
  <tr><th>From</th><th>To</th><th>Distance</th></tr>
  <tr><td>(a+1)</td><td>a+1</td><td>0</td></tr>
  <tr><td>a+1</td><td>(a+1)</td><td>2</td></tr>
  <tr><td>np.sum(a, axis=1)</td><td>np.sum(a, axis=0)</td><td>1</td></tr>
  <tr><td>np.sum(a)</td><td>np.sum(a, axis=1)</td><td>4</td></tr>
  <tr><td>a</td><td>np.sum(a)</td><td>3</td></tr>
  <tr><td>np.sum(a)</td><td>a</td><td>0</td></tr>
</table>
