# Notes 1 November 

Counting things

In [1]:
%matplotlib inline
import numpy as np
import pylab

Simulate rolling a six-sided die

In [4]:
np.random.seed(0)
rolls = np.random.randint(1,7,20)
rolls

array([5, 6, 1, 4, 4, 4, 2, 4, 6, 3, 5, 1, 1, 5, 3, 2, 1, 2, 6, 2])

Write a function to count the number of times each number appears in a sequence. Your function might return array([0, 4, 4, 2, 4, 3, 3]) for the input array([5, 6, 1, 4, 4, 4, 2, 4, 6, 3, 5, 1, 1, 5, 3, 2, 1, 2, 6, 2]) because 0 occurred not at all, 1 occurs 4 times, 2 occurs 4 times, etc.

First let's count only the 5's.

In [5]:
def count5(seq):
    count = 0
    for i in range(len(seq)):
        if seq[i] == 5:
            count = count + 1
    return count

count5(rolls)
    

3

In [6]:
def count5n(seq):
    return np.count_nonzero(seq == 5)
count5n(rolls)

3

In [7]:
def count(seq):
    result = []
    for n in range(1,7):
        result.append(np.count_nonzero(seq == n))
    return result
count(rolls)

[4, 4, 2, 4, 3, 3]

In [8]:
def count(seq):
    result = []
    for n in range(1,7):
        count = 0
        for i in range(len(seq)):
            if seq[i] == n:
                count = count + 1
        result.append(count)
    return result
count(rolls)

[4, 4, 2, 4, 3, 3]

In [9]:
def count(seq):
    result = []
    for n in range(np.min(seq),np.max(seq)+1):
        count = 0
        for i in range(len(seq)):
            if seq[i] == n:
                count = count + 1
        result.append(count)
    return result
count(rolls)

[4, 4, 2, 4, 3, 3]

In [10]:
count(np.random.randint(10,100,20))

[2,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 2,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1]

In [11]:
def count(seq):
    result = []
    for n in range(0,np.max(seq)+1):
        count = 0
        for i in range(len(seq)):
            if seq[i] == n:
                count = count + 1
        result.append(count)
    return result
count(rolls)

[0, 4, 4, 2, 4, 3, 3]

In [18]:
count(np.random.randint(10,100,20))

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 1]

In [13]:
np.bincount(rolls)

array([0, 4, 4, 2, 4, 3, 3])

In [19]:
def count(seq):
    result = np.zeros(np.max(seq)+1, dtype=int)
    for i in range(len(seq)):
        n = seq[i]
        result[n] = result[n] + 1
    return result
count(rolls)
        

array([0, 4, 4, 2, 4, 3, 3])

In [21]:
def countDecorated(seq):
    result = np.zeros(np.max(seq)+1, dtype=int)
    print(result)
    for i in range(len(seq)):
        n = seq[i]
        result[n] = result[n] + 1
        print(result)
    return result
countDecorated(rolls)

[0 0 0 0 0 0 0]
[0 0 0 0 0 1 0]
[0 0 0 0 0 1 1]
[0 1 0 0 0 1 1]
[0 1 0 0 1 1 1]
[0 1 0 0 2 1 1]
[0 1 0 0 3 1 1]
[0 1 1 0 3 1 1]
[0 1 1 0 4 1 1]
[0 1 1 0 4 1 2]
[0 1 1 1 4 1 2]
[0 1 1 1 4 2 2]
[0 2 1 1 4 2 2]
[0 3 1 1 4 2 2]
[0 3 1 1 4 3 2]
[0 3 1 2 4 3 2]
[0 3 2 2 4 3 2]
[0 4 2 2 4 3 2]
[0 4 3 2 4 3 2]
[0 4 3 2 4 3 3]
[0 4 4 2 4 3 3]


array([0, 4, 4, 2, 4, 3, 3])

In [20]:
rolls

array([5, 6, 1, 4, 4, 4, 2, 4, 6, 3, 5, 1, 1, 5, 3, 2, 1, 2, 6, 2])

In [22]:
d = {}
d

{}

In [23]:
d['foo'] = 'hello world'
d

{'foo': 'hello world'}

In [24]:
d['foo']

'hello world'

In [25]:
d['bar']

KeyError: 'bar'

In [26]:
d[5] = 25
d

{'foo': 'hello world', 5: 25}

In [27]:
d[1234567] = 'all good children go to heaven'

In [28]:
d

{'foo': 'hello world', 5: 25, 1234567: 'all good children go to heaven'}